name: Magic Number Workflow

on:
  workflow_dispatch: # This allows the workflow to be triggered manually.

jobs:
  magic-number-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print our slogan
        env:
          SLOGAN: ${{ vars.SLOGAN }}
        run: |
          echo "Our slogan: $SLOGAN"

      - name: Reveal our magic number
        env:
          MY_MAGIC_NUMBER: ${{ secrets.MY_MAGIC_NUMBER }}
        run: |
          echo "The magic number is: $MY_MAGIC_NUMBER"
