name: Magic Number Guessing Game

on:
  workflow_dispatch: # This allows the workflow to be triggered manually.
    inputs:
      user_guess:
        description: "Enter your guess for the magic number" # Prompt for user input
        required: true
        type: string

jobs:
  magic-number-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print our slogan
        env:
          SLOGAN: ${{ vars.SLOGAN }}
        run: |
          echo "Our slogan: $SLOGAN"

      - name: Guess the magic number
        env:
          MY_MAGIC_NUMBER: ${{ secrets.MY_MAGIC_NUMBER }}
        run: |
          USER_GUESS=${{ github.event.inputs.user_guess }}
          if [ "$USER_GUESS" -eq "$MY_MAGIC_NUMBER" ]; then
            echo "🎉 Congratulations! You guessed the magic number: $MY_MAGIC_NUMBER"
          else
            echo "❌ Sorry, that's not correct. The magic number is $MY_MAGIC_NUMBER"
          fi
